baseurl: /HC26-Castillo-Alberto-Senior-Project

remote_theme: andrewbanchich/forty-jekyll-theme
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-include-cache

title: HC26 Senior Project
description: Project site




